### ISSUE TITLE
Link start/arrival point as a hut or parking lot after the hike is already created

### ISSUE THREAD

**Issue by eelielisa** [RemiChbrnt/polito-se2-22-03-Hike-Tracker#18]
In general, from your gpx file which you upload, you could get the coordinates of start and end points. then you should link the two points with existed huts or parking lots.
By the way, all the forms are cute, but it's better to keep them in consistency as a same size.

**Comment by CodingNdStuff** [comment]
Thank you for your feedback. The functionality has been implemented: The form autofills and if the coordinates match an existing location it allows you to select it.
