### ISSUE TITLE
User Story #1 | Filter improvement, ability to save previous filter arguments.

### ISSUE THREAD

**Issue by xose-aka** [RemiChbrnt/polito-se2-22-03-Hike-Tracker#8]

**Comment by wrooklyn** [comment]
It is not possible to save previous filter arguments. However, when you select new filters they're applied to the whole list and not on the filtered ones, so you could reselect previous filter arguments in order to get the same result. This said, we'll take into consideration an improvement.

**Comment by wrooklyn** [comment]
It is not possible to save previous filter arguments. However, when you select new filters they're applied to the whole list and not on the filtered ones, so you could reselect previous filter arguments in order to get the same result. This said, we'll take into consideration an improvement.
